# Generated by Django 5.2.11 on 2026-02-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0011_alter_customerloan_id_alter_loancategory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_payments', to='loanApp.loanrequest')),
            ],
            options={
                'ordering': ['installment_no'],
            },
        ),
    ]
