# Generated by Django 5.2.11 on 2026-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0012_emipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
    ]
