# Generated by Django 5.2.11 on 2026-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0013_loanrequest_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='category',
            field=models.CharField(choices=[('out', 'Loan Disbursement (Out)'), ('in', 'EMI Collection (In)')], default='in', max_length=10),
        ),
    ]
