# Generated by Django 5.2.11 on 2026-04-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0014_loantransaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='payment_type',
            field=models.CharField(choices=[('interest', 'Interest Payment'), ('principal', 'Loan Repayment (Principal)')], default='interest', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='payable_loan',
            field=models.PositiveIntegerField(default=0, help_text='Total payable amount including interest in Rs.', verbose_name='Payable Loan (Rs.)'),
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='total_loan',
            field=models.PositiveIntegerField(default=0, help_text='Total loan amount in Rs.', verbose_name='Total Loan (Rs.)'),
        ),
        migrations.AlterField(
            model_name='emipayment',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='Remaining balance in Rs.', max_digits=12, verbose_name='Balance (Rs.)'),
        ),
        migrations.AlterField(
            model_name='emipayment',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, help_text='EMI amount in Rs.', max_digits=12, verbose_name='EMI Amount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='emipayment',
            name='interest_component',
            field=models.DecimalField(decimal_places=2, help_text='Interest component in Rs.', max_digits=12, verbose_name='Interest (Rs.)'),
        ),
        migrations.AlterField(
            model_name='emipayment',
            name='principal_component',
            field=models.DecimalField(decimal_places=2, help_text='Principal component in Rs.', max_digits=12, verbose_name='Principal (Rs.)'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Enter amount in Rs.', verbose_name='Amount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='payment',
            field=models.PositiveIntegerField(default=0, help_text='Enter payment amount in Rs.', verbose_name='Payment Amount (Rs.)'),
        ),
    ]
